import std/strformat
import std/sugar
import std/options
import std/streams
import std/marshal
import std/random
import std/tables
import std/algorithm

import arraymancer
import "../spherogram-nim/src/links"
import "../spherogram-nim/src/invariants"
import nimpy
import scinim/numpyarrays

import features
import utils
import config
import subdivisions
import band
import state

discard """
The error raised when the feature values of a link
cannot be computed because the link has too many
crossings or components.
"""
type DimensionExceededError* = object of ValueError

proc compute_features*[T](
    base_inst: T,
    shape: array[0..1, int],
    features_cls: seq[TensorFeature]
): seq[(string, Tensor[float])] =
    discard """
    Calculates the features describing the link (as opposed
    to describing the band path) from a CrossChange or
    BandMove instance, given the maximum shape of the link
    and a list of additional feature classes.

    Args:
        base_inst: the CrossChange or BandMove instance
            whose link's features are to be calculated
        shape: a pair of integers; shape[0] means the
            maximum number of crossings that any link
            (either given or generated by an end action) can
            have; shape[1] means the maximum number of
            components that any link in the episodes can
            have
        features_cls: a list of classes of additional
            features whose values on base_inst.link are to
            be included

    Returns:
        A list of (feature name, feature value) pairs.

    Raises:
        DimensionExceededError: if the number of crossings
            of base_inst.link exceeds shape[0] or the number
            of components of base_inst.link exceeds shape[1]
    """
    # For diagram-dependent features, use unsimplified link
    var link_for_diagram = base_inst.link
    # For topological invariants, use simplified link
    var link_for_invariants = base_inst.simplified_link
    if (link_for_diagram.crossings.len > shape[0] or
        link_for_diagram.link_components.len > shape[1]):
        raise newException(DimensionExceededError,
                           &"the observation for link {link_for_diagram} cannot be computed because the link exceeds {shape}")
    var gauss = collect:
        for comp_code in link_for_diagram.gauss_code():
            for c in comp_code & @[-500]:
                c
    # when the link is an unlink, the PD code is an empty
    # (1-dimensional) array, but the dimension of any
    # feature must be a function only of shape, so we need
    # to pad the PD code to shape (shape[0], 4)
    var pd_code = link_for_diagram.PD_code()
    var features = @[
        ("PD_code",
         pad(if pd_code.len > 0: pd_code.toTensor() else: zeros[int]([0, 4]),
             [shape[0], 4], -1000).astype(float)),
        ("unlinked_unknot_components",
         [float(link_for_diagram.unlinked_unknot_components)].toTensor()),
        ("num_link_components",
         [float(link_for_diagram.link_components.len)].toTensor()),
        ("num_connected_components",
         [float(base_inst.framework_info.num_conn_comp)].toTensor()),
        ("gauss_code",
         pad(if gauss.len > 0: gauss.toTensor() else: zeros[int]([0]),
             [1, shape[0]*2 + shape[1]], -1000).reshape(shape[0]*2 + shape[1]).astype(float))
    ]
    # the terminal state for the algebraic unknotting number
    # calculations is a knot with Alexander polynomial 1, so
    # we need to include the Alexander polynomial in the
    # observation
    if base_inst.framework == "unknotting-alg":
        features.add((
            "alexander_poly",
            pad(base_inst.framework_info.alex_poly.get().toTensor(),
                [1, shape[0]+1], -1000).reshape(shape[0]+1).astype(float)
        ))
    # crossing signs and writhe are meaningful in every framework
    features &= @[
        ("crossing_signs",
         pad(if link_for_diagram.signs.len > 0: link_for_diagram.signs.toTensor() else: zeros[int]([0]),
             [1, shape[0]], -1000).reshape(shape[0]).astype(float)),
        ("writhe",
         [float(link_for_diagram.writhe())].toTensor())
    ]
    when T is BandMove:
        # the Seifert genus is used to shape rewards in
        # ribbon / slice genera calculations, so we need to
        # include it in the observation
        when hfk_enabled:
            var floer_hom_bundle = [-1000, -1000, -1000]
            if link_for_invariants.link_components.len + link_for_invariants.unlinked_unknot_components == 1:
                var floer_hom = link_for_invariants.knot_floer_homology()
                floer_hom_bundle = [floer_hom.seifert_genus,
                                    floer_hom.nu,
                                    floer_hom.tau]
            features &= @[
                ("seifert_genus",
                 [float(floer_hom_bundle[0])].toTensor()),
                ("nu",
                 [float(floer_hom_bundle[1])].toTensor()),
                ("tau",
                 [float(floer_hom_bundle[2])].toTensor()),
            ]
    # append the values of the optional features listed in `features_cls`,
    # each evaluated on the link it asks for
    for feature_cls in features_cls:
        let link = if feature_cls.need_unsimplified_diagram(): link_for_diagram
                   else: link_for_invariants
        features &= feature_cls.from_link(link, shape)
    return features

discard """
Given a class implementing some kind of band operations on a
link, produces a subclass that can be represented by a
(string, tensor) table for use by the reinforcement learning
environment.

Args:
    T: the class implementing a type of band operations on a
        link

Returns:
    A subclass of T which implements reinforcement
    learning-related features.
"""
type RepresentableState*[T] = ref object of T
    shape*: array[0..1, int]
    features_cls*: seq[TensorFeature]
    features*: seq[(string, Tensor[float])]

proc newRepresentableState*[T](
    band_path: seq[array[0..3, int]],
    faces: seq[SubdividedFace],
    link: Link[int],
    pd_code: seq[array[0..3, int]],
    face0: seq[array[0..3, int]],
    max_twists: int,
    framework: string,
    framework_info: FrameworkInfo,
    shape: array[0..1, int],
    features_cls: seq[TensorFeature],
    features: seq[(string, Tensor[float])],
    simplification_switch: bool = true,
    simplified_link: Option[Link[int]] = none(Link[int])
): RepresentableState[T] =
    discard """
    Initializes an instance of RepresentableState with
    all the fields filled in. This method should not be
    invoked directly.

    Args:
        band_path: list of lists with four elements: the
            first two elements record the edges with
            directions of the band's travel between the
            two faces that the edge bounds (recorded as
            crossing strands) that the band has visited
            so far; a crossing strand, viewed as an
            outgoing ray from its crossing, means that
            the band has gone through the edge of the
            crossing strand from the face on the left
            side of the ray to the face on the right
            side of the ray; the third element records
            the sign (0 for start or end in the band-move
            case, 1 for over or end1 in the crossing
            change case, and -1 for under or end2 in the
            crossing change case); the fourth and final
            element records the number of twists on the
            band after going through this crossing
            strand but before going through any later
            crossing strand, which is positive if the
            twists are counterclockwise and negative if
            they are clockwise
        faces: the function mapping the index of a face
            to the current subdivision of the face by
            the band
        link: the link that the state is concerned with
        pd_code: the PD code of link; appears as the
            first element of self.features
        face0: the function mapping a crossing strand to
            the index of its first face; the first face
            of a crossing strand is defined to be the
            face on the left side of the outgoing ray of
            the crossing strand
        max_twists: the maximum number of twists that we
            can make on the band in total; needed for
            self.check_twist_error
        framework: the type of link invariant to
            calculate; "unknotting" (for the unknotting
            number) means that we allow band operations
            between strands of the same link component
            and terminate when the current link is an 
            unlink; "ribbon" and "strong ribbon" (for the
            ribbon genus and strong ribbon genus
            respectively) also terminate when the current
            link is an unlink; "strong ribbon" additionally
            restricts band moves to same-CCL strands;
            "slice" and "strong slice" are the same as the
            ribbon frameworks with the unknot_birth action
            additionally available;
            "splitting" means that we do not allow band
            operations between strands of the same link
            component and terminate when the current
            link's diagram is completely split into link
            components; "weak splitting" means that we
            allow band operations between strands of the
            same link component and terminate when the
            current link's diagram is completely split
            into link components
        framework_info: information that is only useful
            for the calculation of some link invariants;
            the number of connected components is only
            useful for the (strong and weak) splitting
            numbers, the Alexander polynomial is only useful
            for the algebraic unknotting number, the
            unlinked ccl's are only useful for the ribbon
            and slice genera, and the genera_info
            table is used for (strong) ribbon and (strong)
            slice genus calculations
        shape: a pair of integers; shape[0] means the
            maximum number of crossings that any link
            (either given or generated by an end action)
            can have; shape[1] means the maximum number
            of components that any link in the episodes
            can have
        features_cls: a list of the classes of
            additional features of the link that we are
            using
        features: a list of values of the features of
            link; see compute_features for details
    """
    var band_twist_inst = newBandTwist(
        band_path, faces, link, pd_code, face0, max_twists,
        framework, framework_info, 
        simplification_switch, simplified_link
    )
    return RepresentableState[T](
        band_path: band_twist_inst.band_path,
        faces: band_twist_inst.faces,
        link: band_twist_inst.link,
        simplified_link: band_twist_inst.simplified_link,
        pd_code: band_twist_inst.pd_code,
        face0: band_twist_inst.face0,
        max_twists: band_twist_inst.max_twists,
        framework: band_twist_inst.framework,
        framework_info: band_twist_inst.framework_info,
        simplification_switch: band_twist_inst.simplification_switch,
        shape: shape, features_cls: features_cls,
        features: features
    )

proc representablestate_from_base_state*[T](
    base_inst: T,
    shape: array[0..1, int],
    features_cls: seq[TensorFeature],
    features: seq[(string, Tensor[float])],
    simplification_switch: bool = true,
    simplified_link: Option[Link[int]] = none(Link[int])
): RepresentableState[T] =
    discard """
    Equips a T object base_inst with features and feature
    values. Since this method does not copy its
    arguments, they should not be used again after being
    passed to this method.  (This is like rvalue
    reference arguments in C++.)

    Args:
        base_inst: the T object to equip with features
        shape: a pair of integers; shape[0] means the
            maximum number of crossings that any link
            (either given or generated by an end action)
            can have; shape[1] means the maximum number
            of components that any link in the episodes
            can have
        features_cls: the list of feature classes we are
            augmenting base_inst with
        features: the list of values of the features in
            features_cls

    Returns:
        The upgraded RepresentableState object.
    """
    return newRepresentableState[T](
        base_inst.band_path, base_inst.faces,
        base_inst.link, base_inst.pd_code, base_inst.face0,
        base_inst.max_twists, base_inst.framework,
        base_inst.framework_info, shape, features_cls,
        features, 
        base_inst.simplification_switch,
        some(base_inst.simplified_link)
    )

proc representablestate_from_link*[T](
    link: Link[int],
    max_twists: int = 5,
    framework: string = "unknotting",
    shape: array[0..1, int] = [50, 4],
    features_cls: seq[TensorFeature] = @[],
    simplification_switch: bool = true
): RepresentableState[T] =
    discard """
    Constructs an instance of RepresentableState from a
    link with no band attached.

    Args:
        link: the given link
        max_twists: the maximum number of twists (across
            all the faces, either counterclockwise or
            clockwise) allowed
        framework: the type of link invariant to
            calculate; "unknotting" (for the unknotting
            number) means that we allow band operations
            between strands of the same link component
            and terminate when the current link is an 
            unlink; "ribbon" and "strong ribbon" (for the
            ribbon genus and strong ribbon genus
            respectively) also terminate when the current
            link is an unlink; "strong ribbon" additionally
            restricts band moves to same-CCL strands;
            "slice" and "strong slice" are the same as the
            ribbon frameworks with the unknot_birth action
            additionally available;
            "splitting" means that we do not allow band 
            operations between strands of the same link 
            component and terminate when the current 
            link's diagram is completely split into link
            components; "weak splitting" means that we 
            allow band operations between strands of the
            same link component and terminate when the 
            current link's diagram is completely split 
            into link components
        shape: a pair of integers; shape[0] means the
            maximum number of crossings that any link
            (either given or generated by an end action)
            can have; shape[1] means the maximum number
            of components that any link in the episodes
            can have
        features_cls: a list of the classes of
            additional features of the link that we are
            using
        simplification_switch: if true, the link is
            simplified between states; if false, the link
            is not simplified between states (but features
            and rewards are still computed on simplified
            versions)

    Returns:
        An instance of RepresentableState whose link
        equals link and whose band has not started.
    """
    when T is CrossChange:
        var base_inst = crosschange_from_link(link, max_twists,
                                              framework,
                                              none(seq[int]),
                                              simplification_switch)
    when T is BandMove:
        var base_inst = bandmove_from_link(link, max_twists,
                                           framework,
                                           none(seq[int]),
                                           simplification_switch)
    return representablestate_from_base_state(
        base_inst, shape, features_cls,
        compute_features(base_inst, shape, features_cls),
        base_inst.simplification_switch,
        some(base_inst.simplified_link)
    )

type
    CrossChangeState* = RepresentableState[CrossChange]
    BandMoveState* = RepresentableState[BandMove]

method copy*(self: CrossChangeState): CrossChangeState {.base.} =
    return representablestate_from_base_state(
        CrossChange(self).copy(), self.shape, self.features_cls,
        self.features
    )

method copy*(self: BandMoveState): BandMoveState {.base.} =
    return representablestate_from_base_state(
        BandMove(self).copy(), self.shape, self.features_cls,
        self.features
    )

proc to_seq*[T](self: RepresentableState[T]): seq[(string, Tensor[float])] =
    discard """
    Converts self to a sequence of tensors by
    - Joining the values of the mutable features (band
      path, total twists and band matrix) with the
      pre-computed values of the immutable features (PD
      code, Gauss code, etc.)
    - Returning the list of (feature name, feature value)
      pairs

    Returns:
        A sequence of tensors representing self.
    """
    var truncated_band_path = collect:
        for t in self.band_path:
            t[0 ..< 3]
    var band_path = pad(if truncated_band_path.len > 0: truncated_band_path.toTensor() else: zeros[int]([0, 3]),
                        [2*self.shape[0], 3], -1000)
    var twists = collect:
        for t in self.band_path:
            t[3]
    var total_twists = sum(twists)
    var band_matrix = newTensorWith([self.link.crossings.len, 4], -10)
    for band_node in self.band_path:
        band_matrix[band_node[0], band_node[1]] = band_node[2]
    band_matrix = pad(band_matrix, [self.shape[0], 4], -1000)
    return @[
        ("band_path", band_path.astype(float)),
        ("total_twists", [float(total_twists)].toTensor()),
        ("band_matrix", band_matrix.astype(float))
    ] & self.features

proc mdp_to_seq*[T](self: RepresentableState[T]): seq[(string, Tensor[float])] =
    discard """
    Converts to tensors the part of the state that to_seq
    leaves out although the legal actions, the next state
    or the reward depend on it: the twists of every band
    segment, row by row with band_path, the crossing
    number of the simplified link and, for band moves, the
    connected component label (CCL) of every link
    component, one genera_info row per CCL and the current
    genus.

    The genera_info rows are sorted by CCL.
    
    Returns:
        A sequence of (feature name, feature value) pairs.
    """
    var twists = collect:
        for t in self.band_path:
            t[3]
    var features = @[
        ("band_twists",
         pad(if twists.len > 0: twists.toTensor() else: zeros[int]([0]),
             [1, 2*self.shape[0]], -1000).reshape(2*self.shape[0]).astype(float)),
        ("simplified_num_crossings",
         [float(self.simplified_link.crossings.len)].toTensor())
    ]
    when T is BandMove:
        var ccls = collect:
            for comp in self.link.link_components:
                comp.extra_info
        var labels = collect:
            for ccl in self.framework_info.genera_info.keys:
                ccl
        labels.sort()
        var rows = collect:
            for ccl in labels[0 ..< min(labels.len, self.shape[1])]:
                let gi = self.framework_info.genera_info[ccl]
                @[ccl, gi.num_end_actions, gi.num_init_comps,
                  gi.num_curr_comps, gi.num_orig_comps]
        features &= @[
            ("component_ccl",
             pad(if ccls.len > 0: ccls.toTensor() else: zeros[int]([0]),
                 [1, self.shape[1]], -1000).reshape(self.shape[1]).astype(float)),
            ("genera_info",
             pad(if rows.len > 0: rows.toTensor() else: zeros[int]([0, 5]),
                 [self.shape[1], 5], -1000).astype(float)),
            ("current_genus",
             [float(BandMove(self).compute_current_answer(self.link, 0))].toTensor())
        ]
    return features

method next_state*(
    self: CrossChangeState,
    action: string
): CrossChangeState {.base.} =
    var base_inst = CrossChange(self).next_state(action)
    var features: seq[(string, Tensor[float])]
    if get_act_type(action) == "end":
        features = compute_features(
            base_inst, self.shape, self.features_cls
        )
    else:
        features = self.features
    return representablestate_from_base_state(
        base_inst, self.shape, self.features_cls, features
    )

method next_state*(
    self: BandMoveState,
    action: string
): BandMoveState {.base.} =
    var base_inst = BandMove(self).next_state(action)
    var features: seq[(string, Tensor[float])]
    # a birth changes the diagram too (the birthed unknot is
    # joined into it), so the features must be recomputed
    if get_act_type(action) in ["end", "birth"]:
        features = compute_features(
            base_inst, self.shape, self.features_cls
        )
    else:
        features = self.features
    return representablestate_from_base_state(
        base_inst, self.shape, self.features_cls, features
    )

proc cls_name*[T](self: RepresentableState[T]): string =
    return &"RepresentableState<{T(self).cls_name()}>"

proc `$`*[T](obj: RepresentableState[T]): string =
    var features_cls_str = collect:
        for c in obj.features_cls:
            c.cls_name()
    return &"{T(obj)}shape={obj.shape}\nadditional feature classes={features_cls_str}\nfeature values={obj.features}\n"

proc crosschangestate_from_link*(
    link_json: string,
    max_twists: int,
    framework: string,
    shape: array[0..1, int],
    features_cls_string: seq[string],
    simplification_switch: bool = true
): CrossChangeState {.exportpy.} =
    var link = decode_link(link_json)
    var features_cls = newSeq[TensorFeature]()
    for feature_cls_string in features_cls_string:
        features_cls.add(decode_cls_name(feature_cls_string))
    return representablestate_from_link[CrossChange](
        link, max_twists, framework, shape, features_cls, simplification_switch
    )

proc bandmovestate_from_link*(
    link_json: string,
    max_twists: int,
    framework: string,
    shape: array[0..1, int],
    features_cls_string: seq[string],
    simplification_switch: bool = true
): BandMoveState {.exportpy.} =
    var link = decode_link(link_json)
    var features_cls = newSeq[TensorFeature]()
    for feature_cls_string in features_cls_string:
        features_cls.add(decode_cls_name(feature_cls_string))
    return representablestate_from_link[BandMove](
        link, max_twists, framework, shape, features_cls, simplification_switch
    )

proc crosschangestate_check_action_error*(
    obj: CrossChangeState,
    action: string
): bool {.exportpy.} =
    return obj.check_action_error(action)

proc bandmovestate_check_action_error*(
    obj: BandMoveState,
    action: string
): bool {.exportpy.} =
    return obj.check_action_error(action)

proc crosschangestate_next_state*(
    obj: CrossChangeState,
    action: string
): (string, CrossChangeState) {.exportpy.} =
    try:
        var res = obj.next_state(action)
        return ("", res)
    except DimensionExceededError:
        return (getCurrentExceptionMsg(), obj)

proc bandmovestate_next_state*(
    obj: BandMoveState,
    action: string
): (string, BandMoveState) {.exportpy.} =
    try:
        var res = obj.next_state(action)
        return ("", res)
    except DimensionExceededError:
        return (getCurrentExceptionMsg(), obj)

proc crosschangestate_to_list*(
    obj: CrossChangeState
): seq[(string, NumpyArray[float])] {.exportpy.} =
    return collect:
        for (feature_name, feature_value) in obj.to_seq():
            (feature_name, feature_value.toNdArray())

proc bandmovestate_to_list*(
    obj: BandMoveState
): seq[(string, NumpyArray[float])] {.exportpy.} =
    return collect:
        for (feature_name, feature_value) in obj.to_seq():
            (feature_name, feature_value.toNdArray())

proc crosschangestate_mdp_to_list*(
    obj: CrossChangeState
): seq[(string, NumpyArray[float])] {.exportpy.} =
    return collect:
        for (feature_name, feature_value) in obj.mdp_to_seq():
            (feature_name, feature_value.toNdArray())

proc bandmovestate_mdp_to_list*(
    obj: BandMoveState
): seq[(string, NumpyArray[float])] {.exportpy.} =
    return collect:
        for (feature_name, feature_value) in obj.mdp_to_seq():
            (feature_name, feature_value.toNdArray())

proc crosschangestate_is_terminal*(
    obj: CrossChangeState
): bool {.exportpy.} =
    return obj.is_terminal()

proc bandmovestate_is_terminal*(
    obj: BandMoveState
): bool {.exportpy.} =
    return obj.is_terminal()

proc bandmovestate_has_unfused_birth_components*(
    obj: BandMoveState
): bool {.exportpy.} =
    return obj.has_unfused_birth_components()

proc crosschangestate_link*(
    obj: CrossChangeState
): string {.exportpy.} =
    return encode_link(obj.link)

proc bandmovestate_link*(
    obj: BandMoveState
): string {.exportpy.} =
    return encode_link(obj.link)

proc crosschangestate_link_num_crossings*(
    obj: CrossChangeState
): int {.exportpy.} =
    return obj.link.crossings.len

proc crosschangestate_simplified_link_num_crossings*(
    obj: CrossChangeState
): int {.exportpy.} =
    return obj.simplified_link.crossings.len

proc bandmovestate_link_num_crossings*(
    obj: BandMoveState
): int {.exportpy.} =
    return obj.link.crossings.len

proc bandmovestate_simplified_link_num_crossings*(
    obj: BandMoveState
): int {.exportpy.} =
    return obj.simplified_link.crossings.len

proc crosschangestate_link_unlinked_unknot_components*(
    obj: CrossChangeState
): int {.exportpy.} =
    return obj.link.unlinked_unknot_components

proc bandmovestate_link_unlinked_unknot_components*(
    obj: BandMoveState
): int {.exportpy.} =
    return obj.link.unlinked_unknot_components

proc crosschangestate_band_path*(
    obj: CrossChangeState
): seq[array[0..3, int]] {.exportpy.} =
    return obj.band_path

proc bandmovestate_band_path*(
    obj: BandMoveState
): seq[array[0..3, int]] {.exportpy.} =
    return obj.band_path

proc crosschangestate_num_conn_comp*(
    obj: CrossChangeState
): int {.exportpy.} =
    return obj.framework_info.num_conn_comp

proc bandmovestate_num_conn_comp*(
    obj: BandMoveState
): int {.exportpy.} =
    return obj.framework_info.num_conn_comp

proc bandmovestate_strand_ccls*(
    obj: BandMoveState
): (seq[array[0..3, int]], seq[int]) {.exportpy.} =
    discard """
    Gives the connected component label (CCL) of the
    surface component on which each crossing strand of
    the state's link lies, and the CCLs of the link's
    unlinked unknot components. verify_band_paths.py
    reads these labels to tell surface components apart
    and recomputes the genus itself, without genera_info.

    Returns:
        A pair: for each crossing, in order, the CCLs of
        its strands 0 to 3; and the CCLs of the unlinked
        unknot components.
    """
    var strand_ccls = newSeq[array[0..3, int]]()
    for c in 0 ..< obj.link.crossings.len:
        var row: array[0..3, int]
        for s in 0 .. 3:
            row[s] = get_strand_ccl(obj.link, c, s)
        strand_ccls.add(row)
    return (strand_ccls,
            obj.framework_info.unlinked_ccl.get(newSeq[int]()))

proc crosschangestate_compute_current_answer*(
    obj: CrossChangeState,
    init_link_json: string,
    num_end_actions: int
): int {.exportpy.} =
    var init_link = decode_link(init_link_json)
    return obj.compute_current_answer(init_link, num_end_actions)

proc bandmovestate_compute_current_answer*(
    obj: BandMoveState,
    init_link_json: string,
    num_end_actions: int
): int {.exportpy.} =
    var init_link = decode_link(init_link_json)
    return obj.compute_current_answer(init_link, num_end_actions)

proc crosschangestate_is_unlink*(
    obj: CrossChangeState
): bool {.exportpy.} =
    return obj.is_unlink()

proc bandmovestate_is_unlink*(
    obj: BandMoveState
): bool {.exportpy.} =
    return obj.is_unlink()

proc crosschangestate_terminal_state_message*(
    obj: CrossChangeState,
    num_end_actions: int,
    answer: int
): string {.exportpy.} =
    return obj.terminal_state_message(num_end_actions, answer)

proc bandmovestate_terminal_state_message*(
    obj: BandMoveState,
    num_end_actions: int,
    answer: int
): string {.exportpy.} =
    return obj.terminal_state_message(num_end_actions, answer)

proc crosschangestate_random_walk_transition*(
    obj: CrossChangeState,
    p_twist: float,
    p_end: float
): (bool, string) {.exportpy.} =
    var res = obj.random_walk_transition(p_twist, p_end)
    if res.isNone:
        return (false, "")
    return (true, res.get())

proc bandmovestate_random_walk_transition*(
    obj: BandMoveState,
    p_twist: float,
    p_end: float
): (bool, string) {.exportpy.} =
    var res = obj.random_walk_transition(p_twist, p_end)
    if res.isNone:
        return (false, "")
    return (true, res.get())

proc crosschangestate_to_string*(
    obj: CrossChangeState
): string {.exportpy.} =
    return $obj

proc bandmovestate_to_string*(
    obj: BandMoveState
): string {.exportpy.} =
    return $obj

proc crosschangestate_max_twists*(
    obj: CrossChangeState
): int {.exportpy.} =
    return obj.max_twists

proc bandmovestate_max_twists*(
    obj: BandMoveState
): int {.exportpy.} =
    return obj.max_twists

proc crosschangestate_action_masks*(
    obj: CrossChangeState
): seq[bool] {.exportpy.} =
    var mask = newSeq[bool](obj.shape[0] * 20 + 2)
    if obj.band_path.len == 0:
        for c in 0 ..< obj.link.crossings.len:
            for s in 0 ..< 4:
                mask[(c*4 + s)*5] = true
    else:
        let cur_strand = (obj.band_path[obj.band_path.len-1][0],
                          obj.band_path[obj.band_path.len-1][1])
        for (c, s) in obj.feasible_next_strands(cur_strand):
            if not obj.check_over_under_error(c, s):
                mask[(c*4 + s)*5 + 1] = true
                mask[(c*4 + s)*5 + 2] = true
            if not obj.check_end_errors(c, s):
                mask[(c*4 + s)*5 + 3] = true
                mask[(c*4 + s)*5 + 4] = true
        for (i, sign) in [(0, 1), (1, -1)]:
            if not obj.check_twist_error(sign):
                mask[obj.shape[0]*20 + i] = true
    return mask

proc bandmovestate_action_masks*(
    obj: BandMoveState
): seq[bool] {.exportpy.} =
    # the slice frameworks have one extra action at the last
    # index: unknot_birth, legal exactly while no band is in
    # progress (mirrors check_birth_error); the mask length
    # must match the env's action count
    let has_birth = obj.framework in ["slice", "strong slice"]
    var mask = newSeq[bool](obj.shape[0] * 24 + (if has_birth: 3 else: 2))
    if obj.band_path.len == 0:
        for c in 0 ..< obj.link.crossings.len:
            for s in 0 ..< 4:
                mask[(c*4 + s)*5] = true
        if has_birth:
            mask[obj.shape[0]*24 + 2] = true
    else:
        let cur_strand = (obj.band_path[obj.band_path.len-1][0],
                          obj.band_path[obj.band_path.len-1][1])
        for (c, s) in obj.feasible_next_strands(cur_strand):
            if not obj.check_over_under_error(c, s):
                mask[(c*4 + s)*5 + 1] = true
                mask[(c*4 + s)*5 + 2] = true
            if not obj.check_end_error(c, s, 0):
                mask[obj.shape[0]*20 + 2 + (c*4 + s)] = true
            if not obj.check_end_error(c, s, 1):
                mask[(c*4 + s)*5 + 3] = true
            if not obj.check_end_error(c, s, -1):
                mask[(c*4 + s)*5 + 4] = true
        for (i, sign) in [(0, 1), (1, -1)]:
            if not obj.check_twist_error(sign):
                mask[obj.shape[0]*20 + i] = true
    return mask

proc nim_rand_state*(): string {.exportpy.} =
    var s = newStringStream("")
    store(s, randState())
    s.setPosition(0)
    return s.readAll()

proc nim_randomize*(): void {.exportpy.} =
    randomize()

proc nim_set_seed*(seed: int): void {.exportpy.} =
    discard """
    Seeds the random number generator of this compiled
    module, which the transitions (through the
    simplification of spherogram-nim) and the random walk
    steps of the mixed agent draw from. agent.so and
    representable.so each hold their own generator, so a
    process using both seeds both.

    Args:
        seed: a positive integer; equal seeds give equal
            random streams

    Raises:
        ValueError: if seed is not positive
    """
    if seed <= 0:
        raise newException(ValueError, &"seed {seed} is not positive")
    randomize(seed)

proc band_get_act_type*(
    action: string
): string {.exportpy.} =
    return get_act_type(action)

proc nim_set_random_state*(state_str: string): void {.exportpy.} =
    # Restore the Nim default RNG to a previously saved state.
    # ``state_str`` must be a string returned by ``nim_rand_state()``.
    var s = newStringStream(state_str)
    var r: Rand
    load(s, r)
    randState() = r

